# Generated by Django 3.2.2 on 2021-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('temperature', models.IntegerField()),
                ('dry_cough', models.BooleanField()),
                ('taste', models.BooleanField()),
                ('breathless', models.BooleanField()),
            ],
        ),
    ]
