# Generated by Django 3.2.2 on 2021-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidcombatapp', '0004_auto_20210518_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True, unique=True)),
                ('test_result', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=20, null=True)),
                ('oxygen_level', models.CharField(choices=[('95 or above', '95 or above'), ('Below 95', 'Below 95')], max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
